name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
      # - run: npm install
      # Transform Globals
      - run: npx token-transformer tokens/tokens.json tokens/input/input.json
      # Transform Site tokens
      # - run: npx token-transformer tokens/tokens.json tokens/input/site.json globals,site globals
      # # Transform Organisms tokens
      # - run: npx token-transformer tokens/tokens.json tokens/input/organisms.json globals,site,organisms globals,site
      # # Transform Elements tokens
      # - run: npx token-transformer tokens/tokens.json tokens/input/elements.json globals,site,organisms,elements globals,site,organisms
      # Run Style Dictionary
      - run: npx style-dictionary build -c sd-config.json
      # Add files that were created during a run, e.g. created files from style dictionary or token-transformer.
      - uses: stefanzweifel/git-auto-commit-action@v4.13.1
        with:
          commit_message: "feat(tokens): process and update tokens"
