name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
      - run: npm install

      # Transform tokens
      # Using token-transformer v0.0.14 (latest is broken)
      - run: npx token-transformer@0.0.14 tokens/tokens.json tokens/input/_global.json global
      - run: npx token-transformer@0.0.14 tokens/tokens.json tokens/input/_site.json global,site global
      - run: npx token-transformer@0.0.14 tokens/tokens.json tokens/input/_components.json global,site,components global,site
      - run: npx token-transformer@0.0.14 tokens/tokens.json tokens/input/_elements.json global,site,components,elements global,site,components
      - run: npx token-transformer@0.0.14 tokens/tokens.json tokens/input/_darkmode.json global,site,components,elements,darkmode global,site,components,elements

      # Run Style Dictionary build
      - run: node sd-build

      # Add files that were created during a run, e.g. created files from style dictionary or token-transformer.
      - uses: stefanzweifel/git-auto-commit-action@v4.13.1
        with:
          commit_message: "feat(tokens): process and update tokens"
